### ISSUE TITLE
Make links Active depending on scroll position (while scrolling manually)

### ISSUE THREAD

**Issue by genyklemberg** [nicky-lenaers/ngx-scroll-to#51] opened 2017-11-10 15:44 UTC
I have this links in navbar:
```
          <li>
            <a [ngx-scroll-to]="'video-block'" class="active">Home</a>
          </li>
          <li>
            <a [ngx-scroll-to]="'about'">About</a>
          </li>
```
and when I'm scrolling manually I want class active to be fired in nav on corresponding items down in html

**Comment by nicky-lenaers** [comment] 2017-11-14 13:56
@genyklemberg Thank you for your issue. However, this issue is not conform the issue guidelines. I too find it difficult to understand your issue properly. Please provide a formatted issue with an inspectable or reproducable problem definition.

Thank you, I'm happy to take a reformulated issue into consideration.

**Comment by nicky-lenaers** [comment] 2017-12-05 09:20
I've been researching this issue. As far as I can tell, you want to add an `active` class to a HTML element based on scroll position. This is *not* something `ngx-scroll-to` covers, because it is not in line with the goal of this plugin.

However, you can achieve something you want using i.e. an **[Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)** to track the scroll position an update HTML accordingly. This should solve you issue.

Closing this issue due to unrelated topic.

**Closed by nicky-lenaers** 2017-12-05 09:20 UTC

**Comment by uloga** [comment] 2019-03-26 07:12
To0 bad that this is not supported since in 90% of cases this is actually how this type of scrolling is used. Diving into fixing this allowed me to recreate the scroll that fits my own needs without using your plugin, which resulted in les code and better performance. You should think about adding that if you want your plugin to be used and get popular. Good luck.
