### ISSUE TITLE
No scrollable parent found for element BUTTON on ngFor

### ISSUE THREAD

**Issue by ofermisk** [nicky-lenaers/ngx-scroll-to#30] opened 2017-08-28 12:30 UTC
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Hi there,
First, thanks for the plugin.
I am having a click issue (as far as i know, i am doing all as written :))...
On click i get "Error: No scrollable parent found for element BUTTON".

**Template**
```
<ion-row  >
    <button *ngFor="let item of data" class="chapter_title" [ngx-scroll-to]="item.title">{{item.title}}</button>
  </ion-row> 
  <ion-row *ngFor="let item of data" id="{{item.title}}">
    <ion-card class="cube_white" >
      <ion-card-header>
        <h3>{{item.title}}</h3>
      </ion-card-header>
      <ion-card-content>
        <div id="{{item.title}}">{{item.content}}</div>
      </ion-card-content>
    </ion-card>
  </ion-row>

```
**The event**
```
public triggerScrollTo($event: Event, itemIndex) {
    console.log(itemIndex);
    const config: ScrollToConfig = {
      target: itemIndex
    }
    this._scrollToService.scrollTo($event, config);
  }
```
**The error output**

> Runtime Error
> No scrollable parent found for element BUTTON
> Stack
> Error: No scrollable parent found for element BUTTON
>     at ScrollToService._getFirstScrollableParent (http://localhost:8100/build/vendor.js:57058:15)
>     at ScrollToService._start (http://localhost:8100/build/vendor.js:56988:30)
>     at ScrollToService.scrollTo (http://localhost:8100/build/vendor.js:56971:21)
>     at http://localhost:8100/build/vendor.js:118910:60
>     at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
>     at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
>     at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
>     at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
>     at invoke (http://localhost:8100/build/polyfills.js:3:10945)
>     at n (http://localhost:8100/build/polyfills.js:2:28549)

## Environment
Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.10.0
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

Browser:
- [x ] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX

**Comment by nicky-lenaers** [comment] 2017-10-05 22:31
@ofermisk Hi, thank you for your issue report! I'll be investigating this soon!

**Comment by nicky-lenaers** [comment] 2017-10-05 22:39
@ofermisk I've tested this within this repository's app and the `*ngFor` works as expected. I've also tested it with a component (non-native HTML element) as a wrapper and that works as well. Do you mind providing a plunkr/example repo so I can investigate?

**Comment by nicky-lenaers** [comment] 2017-11-03 19:57
@ofermisk I've been testing this case for quite some time now, but I can't seem to find the exact reproduction of your issue. Please provide a more detailed Plunker or StackBlitz project that I can look into.

Thanks again for your issue, this is much appreciated.

Closing this issue due to *cannot reproduce*.

**Closed by nicky-lenaers** 2017-11-03 19:57 UTC
Labels: needs: reproduction, priority: high, type: bug
