### ISSUE TITLE
Offset bug for sticky navbar

### ISSUE THREAD

**Issue by INFINITERIUM** [nicky-lenaers/ngx-scroll-to#105] opened 2018-10-25 12:06 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When scrolling to an element using id, and using a sticky top navbar (bootstrap 4), it scrolls to the element without taking the sticky top navbar in account. Resulting in the element's top part to be behind the navbar.

## Expected behavior

Stop the scroll when it's at the sticky navbar, not when it reaches the top of the browser

## Minimal reproduction of the problem with instructions

Sticky top navbar, scroll to a div
## What is the motivation / use case for changing the behavior?

the top part of the element is behind the sticky navbar, at the top of the browser.

## Environment

<pre><code>
Angular version: 5.6.0 (npm -v)

Your version of `@nicky-lenaers/ngx-scroll-to`: 1.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version 62.0.3
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ x ] Edge version 42.17134.1.0
 
For Tooling issues:
- Node version: 8.11.4
- Platform:  Windows

Others:

</code></pre>
IDE: PHPStorm

**Comment by nicky-lenaers** [comment] 2018-10-30 09:57
@INFINITERIUM Thank you for reporting your issue. The situation you describe is actually by design. There are no other HTML elements weighted in the offset calculation, including any sticky elements. This is because it is impossible to know what kind of (sticky) elements to evaluate when determining the scrolling destination and/or offset.

But there is good news! You can, however, achieve your goal by using the `offset` property of this module. You can read more about it here: [directive](https://www.npmjs.com/package/@nicky-lenaers/ngx-scroll-to#advanced-usage---directive) or [service](https://www.npmjs.com/package/@nicky-lenaers/ngx-scroll-to#advanced-usage---service). If you put the height of your sticky bar as the offset, you should be good to go.

Thanks again, closing this issue.

**Closed by nicky-lenaers** 2018-10-30 09:57 UTC
